apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  privileged: true
  allowedCapabilities:
  - "SYS_ADMIN"
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: 'RunAsAny'
  hostPID: false
  hostIPC: false
  hostNetwork: false
  volumes:
    - 'secret'
    - 'hostPath'
  fsGroup:
    rule: 'RunAsAny'
  readOnlyRootFilesystem: false
